# Generated by Django 3.2.7 on 2023-12-08 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartorder',
            name='paid_status',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
